export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDER_START='FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL'

export const AUTHENTICATION_START='AUTHENTICATION_START'
export const AUTHENTICATION_SUCCESS='AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAIL='AUTHENTICATION_FAIL'
export const AUTHENTICATION_LOGOUT='AUTHENTICATION_LOGOUT'
export const AUTHENTICATION_REDIRECTPATH='AUTHENTICATION_REDIRECTPATH'
export const AUTHENTICATION_INITIATE_LOGOUT='AUTHENTICATION_INITIATE_LOGOUT'
export const AUTHENTICATION_CHECK_TIMEOUT='AUTHENTICATION_CHECK_TIMEOUT'

